### ISSUE TITLE
Error when parsing sample schema

### ISSUE THREAD

**Issue by HimanshuZinzuwadia** [thehoneymad/NerdCats.JsonSchemaDefaults#1]
Tried to parse sample schema from https://json-schema.org/learn/miscellaneous-examples.html
Get error on path firstName expected string but got null.  
This is the schema
{
  "$id": "https://example.com/person.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Person",
  "type": "object",
  "properties": {
    "firstName": {
      "type": "string",
      "description": "The person's first name."
    },
    "lastName": {
      "type": "string",
      "description": "The person's last name."
    },
    "age": {
      "description": "Age in years which must be equal to or greater than zero.",
      "type": "integer",
      "minimum": 0
    }
  }
}

**Comment by HimanshuZinzuwadia** [comment]
Never mind, if default value is not specified, it should generate one based on data type instead of failing.

**Comment by leonardo-gooten** [comment]
Hey.. i actually used the same sample data and go the same error..
But I did not understand your second comment..
"it should generate one based on data type instead of failing."
I agree that it should not fail.. it should just generate the field with null ....

So, why did you close the issue?

**Comment by leonardo-gooten** [comment]
Well, for someone else getting here.. This is an alternative that does not throws exception: https://github.com/RicoSuter/NJsonSchema/issues/1425
